In [1]:
import pandas as pd
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import mglearn
import sklearn as sk
import seaborn as sns

In [2]:
load_data = pd.read_csv(r"C:\Users\ACER\Desktop\pyreach\to pc\train.csv")

In [3]:
load_data.shape

(95851, 8)

In [4]:
import random

In [5]:
data = load_data.head(2000)
data.shape

(2000, 8)

In [6]:
data.head()

id                                       comment_text  toxic  \
0  22256635  Nonsense?  kiss off, geek. what I said is true...      1   
1  27450690  "\n\n Please do not vandalize pages, as you di...      0   
2  54037174  "\n\n ""Points of interest"" \n\nI removed the...      0   
3  77493077  Asking some his nationality is a Racial offenc...      0   
4  79357270  The reader here is not going by my say so for ...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [7]:
data.keys()

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate'],
      dtype='object')

In [8]:
data['comment_text'][0]

"Nonsense?  kiss off, geek. what I said is true.  I'll have your account terminated."

In [9]:
data_describe = data[['id','toxic','severe_toxic','obscene','threat','insult','identity_hate']]

In [10]:
# introducing the bag of words model
# the bag of words model allows us to represent text as a numerical fearure vectors.

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
count = CountVectorizer()

In [12]:
# for example
docs = np.array(['The sun is shinning', 'The weather is sweet', 'The sun is shining and the weather is sweet'])
bag = count.fit_transform(docs)

In [13]:
print (count.vocabulary_)

{'the': 6, 'sun': 4, 'is': 1, 'shinning': 3, 'weather': 7, 'sweet': 5, 'shining': 2, 'and': 0}


In [14]:
print (bag.toarray())

[[0 1 0 1 1 0 1 0]
 [0 1 0 0 0 1 1 1]
 [1 2 1 0 1 1 2 1]]


# Assessing word relevancy via term frequency-inverse document frequency

In [15]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf = TfidfTransformer()
np.set_printoptions(precision = 2)
print (tfidf.fit_transform(count.fit_transform(docs)).toarray())

[[ 0.    0.39  0.    0.66  0.5   0.    0.39  0.  ]
 [ 0.    0.43  0.    0.    0.    0.56  0.43  0.56]
 [ 0.39  0.46  0.39  0.    0.3   0.3   0.46  0.3 ]]


In [16]:
data['comment_text']

0       Nonsense?  kiss off, geek. what I said is true...
1       "\n\n Please do not vandalize pages, as you di...
2       "\n\n ""Points of interest"" \n\nI removed the...
3       Asking some his nationality is a Racial offenc...
4       The reader here is not going by my say so for ...
5           Fried chickens \n\nIs dat sum fried chickens?
6       Why can you put English for example on some pl...
7       Guy Fawkes \n\nim a resident in bridgwater and...
8       as far as nicknames go this article is embarra...
9       Woodland Meadows\nGood to hear that you correc...
10      "\n\nWell I just finished a good bit of editin...
11      Discussion should take place on the article ta...
12      Uh oh, you called my bluff. I am intimidated b...
13      "\nWe should also contact the living descendan...
14      " May 2008 (UTC)\n\nNotability of Your New Hea...
15      "\n\nWhile I agree that this article isn't FA ...
16      a Turkish citizen and him having received an a...
17      Please

In [17]:
import re
def preprocessor(text):
    text = re.sub("<[^>]*>", '', text)
    emotions = re.findall('(?::|;|=)(?:-)?(?:\)|\(|D|P)', text)
    
    text = re.sub('[\W] + ','',text.lower()).join(emotions).replace('_', '')
    return text

In [18]:
DataFrame_to_list = data['comment_text'].tolist
print (DataFrame_to_list)

<bound method Series.tolist of 0       Nonsense?  kiss off, geek. what I said is true...
1       "\n\n Please do not vandalize pages, as you di...
2       "\n\n ""Points of interest"" \n\nI removed the...
3       Asking some his nationality is a Racial offenc...
4       The reader here is not going by my say so for ...
5           Fried chickens \n\nIs dat sum fried chickens?
6       Why can you put English for example on some pl...
7       Guy Fawkes \n\nim a resident in bridgwater and...
8       as far as nicknames go this article is embarra...
9       Woodland Meadows\nGood to hear that you correc...
10      "\n\nWell I just finished a good bit of editin...
11      Discussion should take place on the article ta...
12      Uh oh, you called my bluff. I am intimidated b...
13      "\nWe should also contact the living descendan...
14      " May 2008 (UTC)\n\nNotability of Your New Hea...
15      "\n\nWhile I agree that this article isn't FA ...
16      a Turkish citizen and him having 

In [19]:
data['comment_text'][4]

'The reader here is not going by my say so for ethereal vocal style and dark lyrical content. The cited sources in the External Links are saying those things. If you feel the sources are unreliable or I did not represent what they said correctly rewrite or delete it.'

In [20]:
import warnings
warnings.filterwarnings('ignore')

#data['comment_text'] = data['comment_text'].apply(preprocessor)

In [21]:
def tokenizer(text):
    return text.split()
tokenizer('runners like running and this they run')

['runners', 'like', 'running', 'and', 'this', 'they', 'run']

In [22]:
data['tokenized_comment'] = data['comment_text'].apply(tokenizer)

In [23]:
data['tokenized_comment'][1]

['"',
 'Please',
 'do',
 'not',
 'vandalize',
 'pages,',
 'as',
 'you',
 'did',
 'with',
 'this',
 'edit',
 'to',
 'W.',
 'S.',
 'Merwin.',
 'If',
 'you',
 'continue',
 'to',
 'do',
 'so,',
 'you',
 'will',
 'be',
 'blocked',
 'from',
 'editing.',
 '"']

In [24]:
import nltk

In [25]:
len(data['tokenized_comment'])

2000

In [26]:
from nltk.stem.porter import PorterStemmer
porter = PorterStemmer()


def tokenizer_porter(text):
    solution = [porter.stem(word) for word in text]
    return solution


data['tokenized_porter_data'] =data['tokenized_comment'].apply(tokenizer_porter)

In [27]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ACER\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [28]:
from nltk.corpus import stopwords

In [29]:
stop = stopwords.words("english")

# training a logistic regression model for document classification

In [30]:
def re_apply(text):
    solution = [w for w in text if w not in stop]
    return solution

data['tokenized_re_apply'] = data['tokenized_porter_data'].apply(re_apply)
data['tokenized_re_apply'][0]== data['tokenized_porter_data'][0]

False

In [31]:
sentiment = ['toxic','severe_toxic','obscene','threat','insult','identity_hate']

In [32]:
data.keys()

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate', 'tokenized_comment', 'tokenized_porter_data',
       'tokenized_re_apply'],
      dtype='object')

In [33]:
x_train = data.loc[:1499, 'tokenized_re_apply']
y_train = data.loc[:1499, sentiment]
x_test = data.loc[1500:,'tokenized_re_apply']
y_text = data.loc[1500:, sentiment]

In [34]:
from sklearn.grid_search import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(strip_accents = None, lowercase = False, preprocessor = None)

In [35]:
param_grid = [{'vect_ngram_range':[(1,1)], 
              'vect_stop_words':[stop, None],
              'vect_tokenizer': [tokenizer, tokenizer_porter],
              'clf_penalty':['l1','l2'],
              'clf_C': [1.0,10.0,100.0]},
             {'vect_ngram_range':[(1,1)],
             'vect_stop_words':[stop, None],
             'vect_tokenizer':[tokenizer,tokenizer_porter],
             'vect_use_idf':[False],
             'vect_norm':[None],
             'clf_penalty':['l1','l2'],
             'clf_C':[1.0,10.0,100.0]}
             ]
lr_tfidf = Pipeline([('vect',tfidf), ('clf',LogisticRegression(random_state = 0))])

In [36]:
gs_lr_tfidf = GridSearchCV(lr_tfidf, param_grid, scoring = 'accuracy', cv = 2, verbose = 1, n_jobs = -1)

In [37]:
x_train

0       [nonsense?, kiss, off,, geek., I, said, true.,...
1       [", pleas, vandal, pages,, thi, edit, W., S., ...
2       [", ""point, interest"", I, remov, ""point, in...
3       [ask, hi, nation, racial, offence., wow, awar,...
4       [reader, go, say, ether, vocal, style, dark, l...
5            [fri, chicken, Is, dat, sum, fri, chickens?]
6       [whi, put, english, exampl, player, peopl, lik...
7       [guy, fawk, im, resid, bridgwat, go, carniv, e...
8       [far, nicknam, go, thi, articl, embarrassing,,...
9          [woodland, meadow, good, hear, correct, that.]
10      [", well, I, finish, good, bit, editing., I, c...
11      [discuss, take, place, articl, talk, page,, us...
12      [Uh, oh,, call, bluff., I, intimid, number, im...
13      [", We, also, contact, live, descend, adolf, h...
14      [", may, 2008, (utc), notabl, new, heart, A, t...
15      [", I, agre, thi, articl, FA, material,, I, mu...
16      [turkish, citizen, receiv, award(notability), ...
17      [pleas

In [38]:
from sklearn.preprocessing import MultiLabelBinarizer

In [39]:
mult = MultiLabelBinarizer()

In [40]:
help (mult)

Help on MultiLabelBinarizer in module sklearn.preprocessing.label object:

class MultiLabelBinarizer(sklearn.base.BaseEstimator, sklearn.base.TransformerMixin)
 |  Transform between iterable of iterables and a multilabel format
 |  
 |  Although a list of sets or tuples is a very intuitive format for multilabel
 |  data, it is unwieldy to process. This transformer converts between this
 |  intuitive format and the supported multilabel format: a (samples x classes)
 |  binary matrix indicating the presence of a class label.
 |  
 |  Parameters
 |  ----------
 |  classes : array-like of shape [n_classes] (optional)
 |      Indicates an ordering for the class labels
 |  
 |  sparse_output : boolean (default: False),
 |      Set to true if output binary array is desired in CSR sparse format
 |  
 |  Attributes
 |  ----------
 |  classes_ : array of labels
 |      A copy of the `classes` parameter where provided,
 |      or otherwise, the sorted set of classes found when fitting.
 |  
 |  E

In [41]:
mult.get_params

<bound method BaseEstimator.get_params of MultiLabelBinarizer(classes=None, sparse_output=False)>

In [42]:
mult.set_params

<bound method BaseEstimator.set_params of MultiLabelBinarizer(classes=None, sparse_output=False)>

In [ ]:
x_train_mult =mult.fit_transform(x_train)

In [ ]:
gs_lr_tfidf.fit(x_train_mult, y_train)

Fitting 2 folds for each of 48 candidates, totalling 96 fits
