In [12]:
import tensorflow as tf
state = tf.Variable(0, name= 'counter')
constant = tf.constant(1)
new_value = tf.add(state, constant)
update = tf.assign(state, new_value)
init = tf.global_variables_initializer() # must have all variables defined

with tf.Session() as sess:
    sess.run(init)
    for _ in range(4):
        sess.run(update)
        print (sess.run(state))
    sess.close()


1
2
3
4


In [13]:
matrix1 = tf.constant([[3,3,3]])
matrix2 = tf.constant([[2],
                       [2],
                       [4]])
product = tf.matmul(matrix1, matrix2) #np.dot(m1, m2)

sess = tf.Session()
result = sess.run(product)
print (result)
sess.close()

[[24]]


In [14]:
with tf.Session() as sess:
    result2 = sess.run(product)
    print (result2)
    sess.close()

[[24]]


In [ ]:
import numpy as np
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
m, n = housing.data.shape
housing_data_plus_bias = np.c_[np.ones((m,1)), housing.data]


X = tf.constant(housing_data_plus_bias, dtype = tf.float32, name = 'X')
y = tf.constant(housing.target.reshape(-1,1), dtype = tf.float32, name = 'y')
XT = tf.transpose(X)
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT,X)),XT),y)

with tf.Session() as sess:
    theta_value = theta.eval()

In [18]:
value = tf.Variable(tf.random_uniform([6+1,1]), name = 'value')
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print (sess.run(value))
    sess.close()
    

[[ 0.67205572]
 [ 0.13052547]
 [ 0.37136889]
 [ 0.0418582 ]
 [ 0.54744363]
 [ 0.31627011]
 [ 0.18666577]]


In [ ]:
help (tf.reshape)

In [25]:
value_new = tf.Variable(tf.reshape(tf.random_uniform([6+1,1]), (-1,1)), name = 'value')
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print (sess.run(value_new))
    sess.close()
    

[[ 0.01033998]
 [ 0.08700991]
 [ 0.07862008]
 [ 0.34857392]
 [ 0.27331495]
 [ 0.34557152]
 [ 0.65058386]]


In [ ]:
# manually computing the gradients
x = tf.constant(scaled_housing_data_plus_bias, dtype = tf.float32, name = "X")
y = tf.constant(housing.target.reshape(-1,1), dtype = tf.float32,  name = 'y')
theta = tf.Variable(tf.random_uniform([n+1, 1], -1,0,1.0), name = 'theta')
y_pred = tf.matmul(X, theta, name = 'predictions')
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name = 'mse')
gradients = 2/m * tf.matmul(tf.transpose(X), error)
training_op = tf.assign(theta, theta - learning_rate * gradients)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print ("Epoch", epoch, "MSE = ", mse.eval())
        sess.run(training_op)
    best_theta = theta.eval()

In [40]:
help (tf.convert_to_tensor)

Help on function convert_to_tensor in module tensorflow.python.framework.ops:

convert_to_tensor(value, dtype=None, name=None, preferred_dtype=None)
    Converts the given `value` to a `Tensor`.
    
    This function converts Python objects of various types to `Tensor`
    objects. It accepts `Tensor` objects, numpy arrays, Python lists,
    and Python scalars. For example:
    
    ```python
    import numpy as np
    
    def my_func(arg):
      arg = tf.convert_to_tensor(arg, dtype=tf.float32)
      return tf.matmul(arg, arg) + arg
    
    # The following calls are equivalent.
    value_1 = my_func(tf.constant([[1.0, 2.0], [3.0, 4.0]]))
    value_2 = my_func([[1.0, 2.0], [3.0, 4.0]])
    value_3 = my_func(np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float32))
    ```
    
    This function can be useful when composing a new operation in Python
    (such as `my_func` in the example above). All standard Python op
    constructors apply this function to each of their Tensor-valued
   

In [44]:
from sklearn.datasets import load_iris
iris = load_iris()
data = iris.data
target = iris.target
m, n = data.shape
data_bias = np.c_[np.ones((m, 1)), data]

x = tf.constant(data_bias, dtype = tf.float64, name = 'data_bias')
X = tf.convert_to_tensor(x,dtype = tf.float64, name = 'convert_x')

y = tf.constant(target.reshape(-1,1), dtype = tf.float64, name = 'target')
Y = tf.convert_to_tensor(y, dtype = tf.float64, name = 'convert_y')
XT = tf.transpose(X)
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)), XT), Y)
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    theta_value = theta.eval()
    tensor = tf.constant(theta_value)
    value = tensor.eval()
    print (value)
    sess.close()
    

[[ 0.19208399]
 [-0.10974146]
 [-0.04424045]
 [ 0.22700138]
 [ 0.60989412]]


In [35]:
import sklearn as sk
theta = tf.Variable(tf.random_uniform([8, 1], -1.0,1.0), name = 'theta')
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print (sess.run(theta))
    sess.close()

[[-0.79612517]
 [ 0.95541716]
 [-0.79291511]
 [-0.77911663]
 [ 0.48663473]
 [ 0.1560421 ]
 [-0.77413726]
 [ 0.88263321]]


In [36]:
from sklearn.metrics import classification_report

In [38]:
from sklearn.preprocessing import normalize

In [46]:
n_epochs = 1000
learning_rate = 0.01
m, n = data.shape

x = tf.constant(data_bias, dtype = tf.float32, name = 'data_bias')
X = tf.convert_to_tensor(x,dtype = tf.float32, name = 'convert_x')

y = tf.constant(target.reshape(-1,1), dtype = tf.float32, name = 'target')
Y = tf.convert_to_tensor(y, dtype = tf.float32, name = 'convert_y')

theta = tf.Variable(tf.random_uniform([n+1, 1], -1.0,1.0), name = 'theta')
y_pred = tf.matmul(X, theta, name = 'predictions')
error = y_pred - Y
mse = tf.reduce_mean(tf.square(error), name = 'mse')
gradients = 2/m * tf.matmul(tf.transpose(X), error)
training_op = tf.assign(theta, theta - learning_rate * gradients)
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print ("Epoch", epoch, "MSE =", mse.eval())
        sess.run(training_op)
    best_theta = theta.eval()

Epoch 0 MSE = 80.0112
Epoch 100 MSE = 0.0689921
Epoch 200 MSE = 0.0648672
Epoch 300 MSE = 0.0620683
Epoch 400 MSE = 0.0598761
Epoch 500 MSE = 0.0581372
Epoch 600 MSE = 0.056739
Epoch 700 MSE = 0.0555991
Epoch 800 MSE = 0.0546565
Epoch 900 MSE = 0.0538664


In [47]:
# using tensorflow autodiff feature

n_epochs = 1000
learning_rate = 0.01
m, n = data.shape

x = tf.constant(data_bias, dtype = tf.float32, name = 'data_bias')
X = tf.convert_to_tensor(x,dtype = tf.float32, name = 'convert_x')

y = tf.constant(target.reshape(-1,1), dtype = tf.float32, name = 'target')
Y = tf.convert_to_tensor(y, dtype = tf.float32, name = 'convert_y')

theta = tf.Variable(tf.random_uniform([n+1, 1], -1.0,1.0), name = 'theta')
y_pred = tf.matmul(X, theta, name = 'predictions')
error = y_pred - Y
mse = tf.reduce_mean(tf.square(error), name = 'mse')
gradients = tf.gradients(mse, [theta])[0]
training_op = tf.assign(theta, theta - learning_rate * gradients)
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print ("Epoch", epoch, "MSE =", mse.eval())
        sess.run(training_op)
    best_theta = theta.eval()

Epoch 0 MSE = 29.0399
Epoch 100 MSE = 0.139374
Epoch 200 MSE = 0.114833
Epoch 300 MSE = 0.0974138
Epoch 400 MSE = 0.0847403
Epoch 500 MSE = 0.0755087
Epoch 600 MSE = 0.0687736
Epoch 700 MSE = 0.0638497
Epoch 800 MSE = 0.0602404
Epoch 900 MSE = 0.0575853


In [49]:
# using an optimizer
n_epochs = 1000
learning_rate = 0.01
m, n = data.shape

x = tf.constant(data_bias, dtype = tf.float32, name = 'data_bias')
X = tf.convert_to_tensor(x,dtype = tf.float32, name = 'convert_x')

y = tf.constant(target.reshape(-1,1), dtype = tf.float32, name = 'target')
Y = tf.convert_to_tensor(y, dtype = tf.float32, name = 'convert_y')

theta = tf.Variable(tf.random_uniform([n+1, 1], -1.0,1.0), name = 'theta')
y_pred = tf.matmul(X, theta, name = 'predictions')
error = y_pred - Y
mse = tf.reduce_mean(tf.square(error), name = 'mse')
gradients = tf.gradients(mse, [theta])[0]
optimizer = tf.train.GradientDescentOptimizer(learning_rate = learning_rate)

training_op = optimizer.minimize(mse)
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print ("Epoch", epoch, "MSE =", mse.eval())
        sess.run(training_op)
    best_theta = theta.eval()

Epoch 0 MSE = 18.9902
Epoch 100 MSE = 0.0809686
Epoch 200 MSE = 0.0736481
Epoch 300 MSE = 0.0683972
Epoch 400 MSE = 0.0644816
Epoch 500 MSE = 0.0615409
Epoch 600 MSE = 0.0593133
Epoch 700 MSE = 0.0576088
Epoch 800 MSE = 0.0562891
Epoch 900 MSE = 0.0552533


In [51]:
# implementing Mini-batch gradient Descent.
# for this we will need to replace X and Y at every iteration with the next mini-batch.
# the simplest way to do this is to use placeholder nodes.

# placeholders are typically used to pass the training data to tensorflow during training.
A = tf.placeholder(tf.float32, shape = (None, 3))
B = A + 5
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    B_val_1 = B.eval(feed_dict = {A:[[1,2,3]]})
    B_val_2 = B.eval(feed_dict = {A:[[4,5,6],[7,8,9]]})
    sess.close()
    
print (B_val_1)
print (B_val_2)

[[ 6.  7.  8.]]
[[  9.  10.  11.]
 [ 12.  13.  14.]]


In [70]:
data_bias.shape, x.shape, y.shape

((150, 5),
 TensorShape([Dimension(150), Dimension(4)]),
 TensorShape([Dimension(150), Dimension(1)]))

In [71]:
x_place.shape, y_place.shape

(TensorShape([Dimension(150), Dimension(4)]), TensorShape([Dimension(150)]))

In [69]:
x = tf.constant(iris.data, dtype = tf.float32, name = 'data_bias')
X = tf.convert_to_tensor(x,dtype = tf.float32, name = 'convert_x')

y = tf.constant(target.reshape(-1,1), dtype = tf.float32, name = 'target')
Y = tf.convert_to_tensor(y, dtype = tf.float32, name = 'convert_y')

x_place = tf.placeholder(tf.float32, shape = (m, n), name = 'place_x')
y_place = tf.placeholder(tf.float32, shape = (m,), name = 'place_y')

batch_size = 100
n_batches = int(np.ceil(m/batch_size))

def fetch_batch(epoch, batch_index, batch_size):
    x = iris.data
    y = iris.target
    return x, y

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(n_epochs):
        for batch_index in range(n_batches):
            x_batch, y_batch = fetch_batch(epoch, batch_index, batch_size)
            sess.run(training_op, feed_dict = {x_place: x_batch, y_place: y_batch})
            best_theta = theta.eval()
    sess.close()

In [78]:
import os, sys

In [79]:
os.getcwd()

'C:\\SPB_Data\\churn prediction DSN kaggle competition 1 2018\\BestGitWork'

In [82]:
theta = tf.Variable(tf.random_uniform([n+1,1], -1.0,1.0), name = 'theta')
init = tf.global_variables_initializer()
saver = tf.train.Saver()

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(n_epochs):
        if epoch % 100  == 0: # checkpoint every 100 epochs
            save_path = saver.save(sess, "C:\\SPB_Data\\churn prediction DSN kaggle competition 1 2018\\BestGitWork\my_model.ckpt")
            
        sess.run(training_op)
    best_theta = theta.eval()
    save_path = saver.save(sess, "C:\\SPB_Data\\churn prediction DSN kaggle competition 1 2018\\BestGitWork\my_final_model.ckpt")
    
with tf.Session() as sess:
    saver.restore(sess, "C:\\SPB_Data\\churn prediction DSN kaggle competition 1 2018\\BestGitWork\my_final_model.ckpt")
    
    # the following saver only saves or restore only the theta variable under the name weights
    saver = tf.train.Saver({"weights": theta})
    
    # By default the save() method also saves the structure of the graph in the second file with the
    # same name plus a .meta extension. 
    # we can load the graph structure with the following
    saver = tf.train.import_meta_graph("C:\\SPB_Data\\churn prediction DSN kaggle competition 1 2018\\BestGitWork\my_final_model.ckpt.meta")
    
with tf.Session() as sess:
    saver.restore(sess, "C:\\SPB_Data\\churn prediction DSN kaggle competition 1 2018\\BestGitWork\my_final_model.ckpt")

INFO:tensorflow:Restoring parameters from C:\SPB_Data\churn prediction DSN kaggle competition 1 2018\BestGitWork\my_final_model.ckpt
INFO:tensorflow:Restoring parameters from C:\SPB_Data\churn prediction DSN kaggle competition 1 2018\BestGitWork\my_final_model.ckpt


In [88]:
# visualizing the graph and training curves using TensorBoard


from datetime import datetime
now = datetime.utcnow().strftime("%Y%m%d%H%M%S")
root_logdir = 'tf_logs'
logdir = "{}/run-{}".format(root_logdir, now)

x = tf.constant(iris.data, dtype = tf.float32, name = 'data_bias')
X = tf.convert_to_tensor(x,dtype = tf.float32, name = 'convert_x')

y = tf.constant(target.reshape(-1,1), dtype = tf.float32, name = 'target')
Y = tf.convert_to_tensor(y, dtype = tf.float32, name = 'convert_y')

x_place = tf.placeholder(tf.float32, shape = (m, n), name = 'place_x')
y_place = tf.placeholder(tf.float32, shape = (m,), name = 'place_y')

batch_size = 100
n_batches = int(np.ceil(m/batch_size))

def fetch_batch(epoch, batch_index, batch_size):
    x = iris.data
    y = iris.target
    return x, y
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    mse_summary = tf.summary.scalar("MSE", mse)
    file_writer = tf.summary.FileWriter(logdir, tf.get_default_graph())

    for batch_index in range(n_batches):
        x_batch, y_batch = fetch_batch(epoch, batch_index, batch_size)
        if batch_index % 10 == 0:
            summary_str = mse_summary.eval(feed_dict = {x_place: x_batch, y_place: y_batch})
            step = epoch * n_batches + batch_index
            file_writer.add_summary(summary_str, step)
        sess.run(training_op, feed_dict = {x_place: x_batch, y_place: y_batch})


    file_writer.close()
    sess.close()

In [89]:
os.getcwd()

'C:\\SPB_Data\\churn prediction DSN kaggle competition 1 2018\\BestGitWork'

In [93]:
os.listdir('C:\\SPB_Data\\churn prediction DSN kaggle competition 1 2018\\BestGitWork')

['.git',
 '.gitignore',
 '.ipynb_checkpoints',
 'checkpoint',
 'my_final_model.ckpt.data-00000-of-00001',
 'my_final_model.ckpt.index',
 'my_final_model.ckpt.meta',
 'my_model.ckpt.data-00000-of-00001',
 'my_model.ckpt.index',
 'my_model.ckpt.meta',
 'path_files.ipynb',
 'Tensorflow.ipynb',
 'tf_logs']

In [101]:
os.path.isdir('C:\\SPB_Data\\churn prediction DSN kaggle competition 1 2018\\BestGitWork\tf_logs')

False