In [10]:
import pandas as pd

In [11]:
import numpy as np

In [12]:
import sklearn as sk

In [13]:
import matplotlib as plt

In [14]:
import IPython as ip

In [15]:
from sklearn.neighbors import KNeighborsClassifier

In [20]:
np.version.full_version

'1.12.1'

In [21]:
a = np.array([0,1,2,3,4,5])

In [22]:
print (a)

[0 1 2 3 4 5]


In [23]:
a.ndim

1

In [27]:
a.shape
b = np.array([[1,2,3],[3,4,5]])
b.shape
b.ndim

2

In [28]:
a.shape
b.shape

(2, 3)

In [29]:
a.shape

(6,)

In [30]:
b.shape

(2, 3)

In [31]:
b.ndim

2

In [32]:
b = a.reshape((2,3))
print (b)

[[0 1 2]
 [3 4 5]]


In [33]:
c = a.reshape((3,2))
print (c)

[[0 1]
 [2 3]
 [4 5]]


In [34]:
print (b.ndim)
print (c.ndim)

2
2


In [35]:
b.ndim

2

In [36]:
c.ndim

2

In [37]:
b[1][0] = 77
print (b)
print (a)

[[ 0  1  2]
 [77  4  5]]
[ 0  1  2 77  4  5]


In [38]:
c = a.reshape((3,2)).copy()

In [39]:
print (c)

[[ 0  1]
 [ 2 77]
 [ 4  5]]


In [40]:
print (a)

[ 0  1  2 77  4  5]


In [41]:
c[0][0] = -99
print (c)
print (a)
print (b)

[[-99   1]
 [  2  77]
 [  4   5]]
[ 0  1  2 77  4  5]
[[ 0  1  2]
 [77  4  5]]


In [42]:
a*2
a**3

array([     0,      1,      8, 456533,     64,    125], dtype=int32)

In [43]:
a*2

array([  0,   2,   4, 154,   8,  10])

In [44]:
a**3

array([     0,      1,      8, 456533,     64,    125], dtype=int32)

In [45]:
a[np.array([2,3,4])]

array([ 2, 77,  4])

In [46]:
print (a)
a > 4

[ 0  1  2 77  4  5]


array([False, False, False,  True, False,  True], dtype=bool)

In [47]:
a[a>4]

array([77,  5])

In [48]:
a[a>4] = 4

In [49]:
print (a)

[0 1 2 4 4 4]


In [50]:
d = np.array([1,2,np.NAN, 4,5,6])

In [51]:
print (d)

[  1.   2.  nan   4.   5.   6.]


In [52]:
np.isnan(c)

array([[False, False],
       [False, False],
       [False, False]], dtype=bool)

In [54]:
c[-np.isnan(c)]

C:\Users\ACER\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
  """Entry point for launching an IPython kernel.


array([-99,   1,   2,  77,   4,   5])

In [55]:
print (c)

[[-99   1]
 [  2  77]
 [  4   5]]


In [57]:
import timeit
normal_py_sec = timeit.timeit('sum(x*x for x in range(1000))', number = 10000)

In [59]:
naive_np_sec = timeit.timeit('sum(na*na)', setup = "import numpy as np; na= np.arange(1000)", number = 10000)

In [60]:
print ("Normal python: %f sec", normal_py_sec)
print ("Naive numpy: %f sec", naive_np_sec)

Normal python: %f sec 2.4833276031056144
Naive numpy: %f sec 2.1472689905733375


In [61]:
good_np_sec = timeit.timeit("na.dot(na)", setup = "import numpy as np; na = np.arange(1000)", number = 10000)

In [62]:
print ("Good python: %f sec", good_np_sec)

Good python: %f sec 0.10317103960011309


In [64]:
a.dtype
b.dtype
c.dtype

dtype('int32')

In [66]:
a.dtype

dtype('int32')

In [67]:
b.dtype

dtype('int32')

In [68]:
c.dtype

dtype('int32')

In [70]:
import scipy, numpy

In [71]:
scipy.version.full_version

'0.19.0'

In [72]:
scipy.dot == numpy.dot

True

In [73]:
scipy.dot is numpy.dot

True

In [74]:
import scipy as sp